name: Test humiologging library

on: [push, pull_request]

jobs:
  test:
    name: "Python ${{ matrix.python-version }}"
    runs-on: ubuntu-latest
    env:
      USING_COVERAGE: '3.8'

    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9]

    steps:
    - uses: actions/checkout@v2

    - uses: actions/cache@v2
      id: cache
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('setup.cfg') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install test dependencies
      # if: steps.cache.outputs.cache-hit != 'true'
      run: |
        set -xe
        python -VV
        python -m site
        python -m pip install --upgrade pip "setuptools<46" wheel
        python -m pip install --upgrade virtualenv tox tox-gh-actions coverage

    - name: Lint with flake8
      run: |
        python -m tox -e flake8-critical

    - name: Test with tox
      run: |
        python -m tox

    - name: "Combine coverage"
      if: "contains(env.USING_COVERAGE, matrix.python-version)"
      run: |
        set -xe
        python -m coverage combine
        python -m coverage xml

    - name: Upload to Codecov
      if: "contains(env.USING_COVERAGE, matrix.python-version)"
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        fail_ci_if_error: true
